apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: multi-agent-config
spec:
  tracing:
    samplingRate: "1"
  httpPipeline:
    handlers:
      - name: cors
        type: middleware.http.cors
  components:
    - name: chat-pubsub
      type: pubsub.redis
      version: v1
      metadata:
        - name: redisHost
          value: localhost:6379
    - name: chat-state
      type: state.redis
      version: v1
      metadata:
        - name: redisHost
          value: localhost:6379